# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_teams', '0002_ownership_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_member', through='django_teams.TeamStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
