# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_teams', '0003_auto_20160906_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='team_member', through='django_teams.TeamStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
